trigger:
  - main

pool:
  name: Default

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
    displayName: 'Use Python 3.10'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest
    displayName: 'Install dependencies'

  - script: ls -l
    displayName: 'List files in working directory'

  - script: pytest tests/
    displayName: 'Run tests'
