trigger:
- main

pool:
  name: Default  # or the exact name of your self-hosted agent pool

steps:
- script: |
    echo "Hello from self-hosted Linux agent!"
    uname -a
  displayName: 'Test agent connectivity'
